# Generated by Django 5.2.11 on 2026-03-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('study_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('enrollment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Phlebotomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('collector_name', models.CharField(max_length=100)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('sputum', 'Sputum'), ('urine', 'Urine'), ('other', 'Other')], max_length=20)),
                ('tube_type', models.CharField(choices=[('EDTA', 'EDTA'), ('LIHEP', 'Li-Hep'), ('SST', 'SST'), ('SODIUM_CITRATE', 'Sodium Citrate'), ('BLOOD_CULTURE', 'Blood Culture'), ('RED_TOP', 'Red Top'), ('URINE_CONTAINER', 'Urine Container'), ('OTHER', 'Other')], max_length=20)),
                ('volume_collected', models.CharField(choices=[('3ML', '3 mL'), ('6ML', '6 mL'), ('10ML', '10 mL'), ('OTHER', 'Other')], max_length=10)),
                ('collection_site', models.CharField(choices=[('venous', 'Venous'), ('capillary', 'Capillary'), ('arterial', 'Arterial')], max_length=20)),
                ('collection_notes', models.CharField(choices=[('SUFFICIENT', 'Sufficient'), ('INSUFFICIENT', 'Insufficient'), ('OTHER', 'Other')], max_length=20)),
                ('collection_notes_other', models.TextField(blank=True)),
                ('consented', models.BooleanField(default=True)),
                ('visit_type', models.CharField(choices=[('screening', 'Screening'), ('baseline', 'Baseline'), ('follow_up', 'Follow-up'), ('exit', 'Exit'), ('unscheduled', 'Unscheduled')], max_length=20)),
                ('sample_collected', models.BooleanField(default=True)),
                ('no_collection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomies_created', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomies', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Phlebotomies',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='SampleProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('reception_date', models.DateField()),
                ('reception_time', models.TimeField()),
                ('tubes_edta', models.PositiveIntegerField(default=0)),
                ('tubes_lihep', models.PositiveIntegerField(default=0)),
                ('tubes_sst', models.PositiveIntegerField(default=0)),
                ('tubes_sodium_citrate', models.PositiveIntegerField(default=0)),
                ('tubes_blood_culture', models.PositiveIntegerField(default=0)),
                ('tubes_red_top', models.PositiveIntegerField(default=0)),
                ('tubes_other', models.PositiveIntegerField(default=0)),
                ('processing_type', models.CharField(choices=[('centrifugation', 'Centrifugation'), ('incubation', 'Incubation'), ('aliquoting', 'Aliquoting'), ('other', 'Other')], max_length=20)),
                ('aliquot_number', models.CharField(blank=True, max_length=50)),
                ('technologist_initials', models.CharField(max_length=10)),
                ('equipment_used', models.CharField(blank=True, choices=[('ref_centrifuge', 'Refrigerated Centrifuge'), ('non_ref_centrifuge', 'Non-Refrigerated Centrifuge'), ('other', 'Other')], max_length=30)),
                ('centrifugation_start', models.DateTimeField(blank=True, null=True)),
                ('centrifugation_end', models.DateTimeField(blank=True, null=True)),
                ('incubation_start', models.DateTimeField(blank=True, null=True)),
                ('incubation_end', models.DateTimeField(blank=True, null=True)),
                ('results_dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('results_dispatched_to', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processings_created', to=settings.AUTH_USER_MODEL)),
                ('phlebotomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='core.phlebotomy')),
            ],
            options={
                'verbose_name_plural': 'Sample Processings',
                'ordering': ['-reception_date'],
            },
        ),
        migrations.CreateModel(
            name='SampleStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('freezer_id', models.CharField(blank=True, max_length=50)),
                ('fridge_id', models.CharField(blank=True, max_length=50)),
                ('shelf_number', models.CharField(blank=True, max_length=20)),
                ('rack_number', models.CharField(blank=True, max_length=20)),
                ('box_number', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('storage_temperature', models.CharField(choices=[('2-8', '2°C to 8°C'), ('-20', '-20°C'), ('-80', '-80°C')], max_length=10)),
                ('date_stored', models.DateField()),
                ('storage_condition', models.CharField(choices=[('good', 'Good'), ('compromised', 'Compromised')], default='good', max_length=15)),
                ('retrieval_datetime', models.DateTimeField(blank=True, null=True)),
                ('retrieved_by', models.CharField(blank=True, max_length=100)),
                ('retrieval_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('compromised', 'Compromised')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages_created', to=settings.AUTH_USER_MODEL)),
                ('processing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='core.sampleprocessing')),
            ],
            options={
                'verbose_name_plural': 'Sample Storages',
                'ordering': ['-date_stored'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('reagent', 'Reagent'), ('consumable', 'Consumable')], max_length=20)),
                ('supplier', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('boxes', 'Boxes'), ('liters', 'Liters'), ('other', 'Other')], max_length=10)),
                ('storage_location', models.CharField(choices=[('main_store', 'Main Store'), ('departmental_store', 'Departmental Store'), ('quarantine_store', 'Quarantine Store')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('condition_received', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='good', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('received_by', models.CharField(max_length=100)),
                ('reception_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'ordering': ['item_name'],
            },
        ),
    ]
